- name: 'Working on subnets yaml {{ _subnets_file }}'
  include_vars:
    file: '{{ _subnets_file }}'
    name: _subnet

- name: Debug out _subnet
  debug:
    var: _subnet
    verbosity: 1

- name: Add to global subnets dict
  set_fact:
               # products dict, or empty dict, plus new k/v 
    subnets: "{{ subnets | default([]) | combine({_subnet.id: _subnet}) }}"
    _orgs: []
    _locations: []
    _domains: []

- name: Debug out subnets
  debug:
    var: subnets
    verbosity: 2

- name: Build orgs list
  set_fact:
    _orgs: "{{ _orgs | default([]) + [ _r.title] }}"
  loop: '{{ _subnet.organizations | default([]) }}'
  loop_control:
    loop_var: _r

- name: Build locations list
  set_fact:
    _locations: "{{ _locations | default([]) + [ _r.title ] }}"
  loop: '{{ _subnet.locations | default([]) }}'
  loop_control:
    loop_var: _r

- name: Build domains list
  set_fact:
    _domains: "{{ _domains | default([]) + [ _r.name ] }}"
  loop: '{{ _subnet.domains | default([]) }}'
  loop_control:
    loop_var: _r

- name: "Create/Update Subnet [{{ _subnet.name }}]"
  theforeman.foreman.subnet:
    username: '{{ satellite_api_username }}'
    password: '{{ satellite_api_password }}' 
    server_url: 'https://{{ ansible_host }}'
    state: present
    organizations: '{{ _orgs }}'
    name: '{{ _subnet.name }}'
    boot_mode:  '{{ _subnet.boot_mode | default(omit, True) }}'  
    cidr: '{{ _subnet.cidr | default(omit, True)}}' 
    description: '{{ _subnet.description | default(omit, True)}}' 
    dns_primary: '{{ _subnet.dns_primary | default(omit, True) }}'
    dns_secondary: '{{ _subnet.dns_secondary | default(omit, True) }}'
    gateway: '{{ _subnet.gateway | default(omit, True) }}'
    ipam: '{{ _subnet.ipam | default(omit, True) }}'
    mask: '{{ _subnet.mask | default(omit, True) }}'
    mtu: '{{ _subnet.mtu | default(omit, True) }}'
    network: '{{ _subnet.network }}'
    network_type: '{{ _subnet.network_type | default(omit, True) }}'
    vlanid: '{{ _subnet.vlanid | int | default(omit, True) }}'
    locations: '{{ _locations }}'
    domains: '{{ _domains }}'
    dhcp_proxy: '{{ _subnet.dhcp | default(omit, True) }}'
    discovery_proxy: '{{ _subnet.discovery | default(omit, True) }}'
    dns_proxy: '{{ _subnet.dns | default(omit, True) }}'
    from_ip: '{{ _subnet.from | default(omit, True) }}'
    to_ip: '{{ _subnet.to | default(omit, True) }}'
    httpboot_proxy: '{{ _subnet.httpboot | default(omit, True) }}'
    template_proxy: '{{ _subnet.template | default(omit, True) }}'
    tftp_proxy: '{{ _subnet.tftp | default(omit, True) }}'
