- name: Process each location yamls
  include_tasks: global_location_read.yml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/locations/*yaml'

- name: Top down, import per depth
  include_tasks: global_location_per_depth.yml
  loop: "{{locations.keys()|sort }}" 
  when: false

- name: Process each domain yaml
  include_tasks: global_domains_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/domains/*.yaml'
  loop_control:
    loop_var: _domains_file

- name: Process each subnets yaml
  include_tasks: global_subnets_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/subnets/*.yaml'
  loop_control:
    loop_var: _subnets_file

- name: Process each compute profile yaml
  include_tasks: global_compute_profiles_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/compute_profiles/*.yaml'
  loop_control:
    loop_var: _compute_profiles_file 

- name: Process each architecture yaml
  include_tasks: global_architectures_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/architectures/*.yaml'
  loop_control:
    loop_var: _architectures_file 

- name: Process each partition table yaml
  include_tasks: global_partition_tables_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/ptables/*.yaml'
  loop_control:
    loop_var: _partition_tables_file 

- name: Process each installation media yaml
  include_tasks: global_installation_medium_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/media/*.yaml'
  loop_control:
    loop_var: _installation_medium_file 

- name: Process each settings yaml
  include_tasks: global_settings_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/settings/*.yaml'
  loop_control:
    loop_var: _settings_file 

- name: Process each users yaml
  include_tasks: global_users_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/global/users/*.yaml'
  loop_control:
    loop_var: _users_file 
