---
- name: Hello World
  debug:
    msg: Hello from Ansible-Role-Satellite-Configuration-Import

- name: create temporary git repository directory
  tempfile:
    state: directory
  register: git_root_dir

- name: Clone existing repository to {{ git_root_dir.path }}
  shell: |
    cd {{ git_root_dir.path }}
    git clone {{ import_git_url }} repo
    cd repo
    git checkout {{ import_git_branch }}

- name: Organizations
  import_tasks: orgs.yml

#- name: Process each compute profile yaml
#  include_tasks: global_compute_profiles_chunk.yaml
#  with_fileglob:
#    - '{{ git_root_dir.path }}/repo/managed/global/compute_profiles/*.yaml'
#  loop_control:
#    loop_var: _compute_profiles_file

