---
- name: Hello World
  debug:
    msg: Hello from Ansible-Role-Satellite-Configuration-Import

- name: create temporary git repository directory
  tempfile:
    state: directory
  register: git_root_dir

- name: Clone existing repository to {{ git_root_dir.path }}
  shell: |
    cd {{ git_root_dir.path }}
    git clone {{ import_git_url }} repo
    cd repo
    git checkout {{ import_git_branch }}

- name: Global context
  import_tasks: global.yml

- name: Organizations context
  import_tasks: organizations.yaml

- name: Cleanup tmp location
  file:
    path: "{{ git_root_dir.path }}"
    state: absent
  when: io_git_keep_repos is undefined or not io_git_keep_repos

