---
- name: Create temporary git repository directory
  tempfile:
    state: directory
  register: git_root_dir

- name: Clone existing repository to {{ git_root_dir.path }}
  shell: |
    cd {{ git_root_dir.path }}
    git clone {{ import_git_url }} repo
    cd repo
    git checkout {{ import_git_branch }}

- name: Global context (early)
  import_tasks: global_early.yml

- name: Organizations context
  import_tasks: organizations.yaml

#- name: Global context (late)
#  import_tasks: global_late.yml

- name: Cleanup tmp location
  file:
    path: "{{ git_root_dir.path }}"
    state: absent
  when: io_git_keep_repos is undefined or not io_git_keep_repos

