
#Content views are special insofar as they are regular or composite
#So while more difficult to handle than n-layer recursive structures, 
# we do have to do with 2 specific layers
#
#After configuring a Content View (which points to the Libraryi by default),
#we go back and a) add a Content View Filter, and b) configure CV Versions.
#
#Configuring a Version has the effect of "promoting" a version, as we attach a version
#to a life cycle environment.
#
# DANGER DANGER DANGER DANGER
#
#     All versions created will be identical, as the configuration,
#     and underlying library content will be identical.
#
# DANGER DANGER DANGER DANGER     
#

- name: initialize facts
  set_fact:
    content_views: []
    content_view_versions: []
    content_view_filters: []

- name: Load each content view yaml
  include_tasks: org_content_view_load_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/organizations/{{ _org.name }}/content_views/*.yaml'
  loop_control:
    loop_var: _content_view_file


- name: Load CV Versions
  include_tasks: org_content_view_versions_load_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/organizations/{{ _org.name }}/content_view_versions/*.yaml'
  loop_control:
    loop_var: _cv_version_file

- name: Load CV Filters
  include_tasks: org_content_view_filters_load_chunk.yaml
  with_fileglob:
    - '{{ git_root_dir.path }}/repo/managed/organizations/{{ _org.name }}/content_view_filters/*.yaml'
  loop_control:
    loop_var: _cv_filter_file

- name: Debug out content_views and content_view_versions
  debug:
    var: content_views
    var: content_view_versions
    var: content_view_filters
    verbosity: 1

- name: Import non-composite CVs
  include_tasks: org_content_view_import_chunk.yaml
  when: not _cv.value.composite
  loop: "{{ content_views|dict2items}}"
  loop_control:
    loop_var: _cv

- name: Import composite CVs
  include_tasks: org_content_view_import_chunk.yaml
  when: _cv.value.composite
  loop: "{{ content_views|dict2items}}"
  loop_control:
    loop_var: _cv

- name: Deal with non-composite CV versions
  include_tasks: org_content_view_versions_chunk.yaml
  when: not _cv.value.composite
  loop: "{{ content_views|dict2items}}"
  loop_control:
    loop_var: _cv

- name: Import composite CVs
  include_tasks: org_content_view_versions_chunk.yaml
  when: _cv.value.composite
  loop: "{{ content_views|dict2items}}"
  loop_control:
    loop_var: _cv
