- name: 'Working on Content Credentials yaml {{ _content_credentials_file }}'
  include_vars:
    file: '{{ _content_credentials_file }}'
    name: _content_credential

- name: Debug out _content_credential
  debug:
    var: _content_credential
    verbosity: 1

- name: Add to global content_credential dict
  set_fact:
               # products dict, or empty dict, plus new k/v 
    content_credentials: "{{ content_credentials | default([]) | combine({_content_credential.id: _content_credential}) }}"

- name: Debug out content_credentials
  debug:
    var: content_credentials
    verbosity: 2

- name: Create/Update Content Credential
  theforeman.foreman.content_credential:
    username: '{{ satellite_api_username }}'
    password: '{{ satellite_api_password }}' 
    server_url: 'https://{{ ansible_host }}'
    state: present
    organization: '{{ _org.name }}'
    name: '{{ _content_credential.name }}'
    content_type: '{{ _content_credential.content_type }}'
    content: '{{ _content_credential.content }}'

